# Generated by Django 5.1.3 on 2024-11-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_merge_20241124_0452'),
        ('apps', '0009_merge_20241124_0742'),
    ]

    operations = [
    ]
