# Generated by Django 5.1.3 on 2024-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_merge_20241124_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingcredentials',
            name='password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
